require:
  - rubocop-performance
  - rubocop-rake

inherit_gem:
  onkcop:
    - "config/rubocop.yml"
    - "config/rspec.yml"
    - "config/performance.yml"

AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable

  Exclude:
    - 'gemfiles/vendor/**/*'

    # c.f. https://github.com/rubocop/rubocop/blob/v1.56.4/config/default.yml#L65-L69
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - '.git/**/*'

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/SharedExamples:
  Enabled: false
